### ISSUE TITLE
THIS IS NOT A ISSUE WITH THIS PROJECT, IT'S ABOUT YOUR PROFILE

### ISSUE THREAD

**Issue by Zacky2613** [CPScript/USB-Ransom#1]
Some words on your profile description are misspelt and same with some grammar issues. 

Here's a fixed version you can copy and paste to fix is this:
`I'm having fun using VBS and batchfile... I'm going to be focusing on making useful tools than malwares, BUT every once and a while it's always fun to make one.`

**Comment by 0u44** [comment]
uhhh... thanks???
